version: '3'

networks:
  nginx_net:
    external:
      name: nginx_net


services:
  web:
    container_name: "archimede_web"
    image: fumaz/ubuntu-20.04
    build: .
    restart: unless-stopped
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app
    command: /usr/src/app/server/server.sh
    networks:
      - nginx_net